// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oglalspirblwvqkzmcxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbGFsc3BpcmJsd3Zxa3ptY3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjY4MjIsImV4cCI6MjA2NTc0MjgyMn0.haLD-iQ-S7IKDPxSBvZxYyudoIbTjyfYUn0Cu09cl0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);